on: [push]

jobs:

  Build:
    runs-on: ubuntu-latest
    name: A job to test the oryks code coverage action

    steps:

      - name: oryks code coverage action
        id: selftest
        uses: twyle/oryks-code-coverage@v0.1.0
        with:
          myinput: lyle

      - name: action output
        run: |
          echo "${{ steps.selftest.outputs.myoutput }}"
