on: [push]

jobs:

  Build:
    runs-on: ubuntu-latest
    name: A job to test the oryks code coverage action

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: oryks code coverage action
        id: selftest
        uses: twyle/oryks-code-coverage@v0.2.0
        with:
          codedirectory: src/
          testdirectory: tests/

      - name: action output
        run: |
          echo "${{ steps.selftest.outputs.testcoverage }}"
